/*DROP TABLE CAPITALS;
DROP TABLE MASKEVENT;
DROP TABLE MANAGER;
DROP TABLE CITY_LANGUAGE;
DROP TABLE COUNTRY_LANGUAGE;
DROP TABLE REVIEW;
DROP TABLE NORMAL_USER;
DROP TABLE LOCATION;
DROP TABLE CITY;
DROP TABLE COUNTRY;
DROP TABLE REVIEWABLE;
DROP TABLE SUPPORTED_LANGUAGES;
DROP TABLE SUPPORTED_EVENTS;
DROP TABLE SUPPORTED_LOCATIONS;
DROP VIEW AverageRating;
*/



/* Event views
CREATE VIEW BarcelonaEvent AS SELECT * FROM MASKEVENT WHERE City LIKE 'Barcelona';
CREATE VIEW ParisEvent as SELECT * FROM MASKEVENT WHERE City LIKE 'PARIS';
*/

/* Cities that speak a language */
/* CREATE VIEW FrenchCity AS SELECT * FROM CITY_LANGUAGE WHERE Lang LIKE 'French';
CREATE VIEW SpanishCity AS SELECT * FROM CITY_LANGUAGE WHERE Lang LIKE 'Spanish';
CREATE VIEW CatalanCity AS SELECT * FROM CITY_LANGUAGE WHERE Lang LIKE 'Catalan';
CREATE VIEW ValencianCity AS SELECT * FROM CITY_LANGUAGE WHERE Lang LIKE 'Valencian';
CREATE VIEW DutchCity AS SELECT * FROM CITY_LANGUAGE WHERE Lang LIKE 'Dutch';
CREATE VIEW GermanCity AS SELECT * FROM CITY_LANGUAGE WHERE Lang LIKE 'German';
CREATE VIEW GaelicCity AS SELECT * FROM CITY_LANGUAGE WHERE Lang LIKE 'Gaelic';
CREATE VIEW EnglishCity AS SELECT * FROM CITY_LANGUAGE WHERE Lang LIKE 'English';
 */


/* AverageRating view */


/*
CREATE VIEW FranceRating AS SELECT * FROM FrenchCity NATURAL JOIN AverageRating;
*/


CREATE TABLE SUPPORTED_LANGUAGES
	(Lang		VARCHAR(15)			NOT NULL,
	PRIMARY KEY (Lang) );
    
CREATE TABLE SUPPORTED_LOCATIONS
	(Location		VARCHAR(15)			NOT NULL,
PRIMARY KEY (Location) );



CREATE TABLE SUPPORTED_EVENTS
	(MASKEvent		VARCHAR(15)	NOT NULL,
PRIMARY KEY (MASKEvent) );

CREATE TABLE COUNTRY
	(Country 			VARCHAR(15)		NOT NULL,
	 Population			INT,
	PRIMARY KEY (Country) );

CREATE TABLE CAPITALS
	(Country			VARCHAR(15)		NOT NULL,
	 City				VARCHAR(15)		NOT NULL,
	PRIMARY KEY (Country, City),
	FOREIGN KEY (Country) REFERENCES COUNTRY (Country) );

CREATE TABLE REVIEWABLE
	(Review_ID		INT					NOT NULL,
	PRIMARY KEY (Review_ID) );

CREATE TABLE NORMAL_USER
	(Username		VARCHAR(15)			NOT NULL,
	 Email			VARCHAR(35)			NOT NULL UNIQUE,
	 UserPassword		VARCHAR(15)			NOT NULL,
	PRIMARY KEY (Username) );


CREATE TABLE REVIEW
	(Username		VARCHAR(15)			NOT NULL,
	Subject         VARCHAR(15),
	 ReviewDate			DATE					NOT NULL,
	 Score			INT,
	 Description		VARCHAR(15),
	 Review_ID		INT					NOT NULL,
	PRIMARY KEY (Username, ReviewDate, Review_ID),
	FOREIGN KEY (Review_ID) REFERENCES REVIEWABLE (Review_ID),
FOREIGN KEY (Username) REFERENCES NORMAL_USER (Username) );

CREATE TABLE COUNTRY_LANGUAGE
	(Country			VARCHAR(15)		NOT NULL,
	 Lang			VARCHAR(15)		NOT NULL,
	PRIMARY KEY (Country, Lang),
	FOREIGN KEY (Country) REFERENCES COUNTRY (Country),
FOREIGN KEY (Lang) REFERENCES SUPPORTED_LANGUAGES (Lang) );

CREATE TABLE CITY
	(Country			VARCHAR(15)		NOT NULL,
	 City				VARCHAR(15)		NOT NULL,
	 Longitude			VARCHAR(15)			NOT NULL,
	 Latitude			VARCHAR(15)			NOT NULL,
	 Review_ID			INT				NOT NULL,
     Population			INT				NOT NULL,
	PRIMARY KEY (Country, City),
	FOREIGN KEY (Country) REFERENCES COUNTRY (Country),
	FOREIGN KEY (Review_ID) REFERENCES REVIEWABLE (Review_ID) );

CREATE TABLE CITY_LANGUAGE
	(Country		VARCHAR(15)		NOT NULL,
	 City			VARCHAR(15)		NOT NULL,
	 Lang		VARCHAR(15)		NOT NULL,
	PRIMARY KEY (Country, City, Lang),
	FOREIGN KEY (Country, City) REFERENCES CITY (Country, City),
FOREIGN KEY (Lang) REFERENCES SUPPORTED_LANGUAGES (Lang) );


CREATE TABLE LOCATION
	(Country			VARCHAR(15)		NOT NULL,
	 City				VARCHAR(15)		NOT NULL,
	 Address			VARCHAR(100)	NOT NULL,
	 Location_Name		VARCHAR(15)		NOT NULL,
	 Cost				DECIMAL(10,2)	NOT NULL,
	 LocationType		VARCHAR(15)		NOT NULL,
	 STD_Discount		tinyint(1)		NOT NULL,
	 Review_ID			INT				NOT NULL,
	PRIMARY KEY (Country, City, Address),
	FOREIGN KEY (Country) REFERENCES COUNTRY (Country),
	FOREIGN KEY (Country, City) REFERENCES CITY (Country, City),
	FOREIGN KEY (Review_ID) REFERENCES REVIEWABLE (Review_ID),
FOREIGN KEY (LocationType) REFERENCES SUPPORTED_LOCATIONS  (Location) );

CREATE TABLE MASKEVENT
	(Country			VARCHAR(15)		NOT NULL,
	 City				VARCHAR(15)		NOT NULL,
	 Address			VARCHAR(100)		NOT NULL,
	 Event_Name			VARCHAR(40)		NOT NULL,
	 EventDate			DATE				NOT NULL,
	 Start_Time			TIME				NOT NULL,
	 End_Time			TIME,
	 STD_Discount		tinyint(1),
	 Description		VARCHAR(300),
	 Category			VARCHAR(15),
     Cost				INT,
	 Review_ID			INT				NOT NULL,
	PRIMARY KEY (Country, City, Address, Event_Name, EventDate, Start_Time),
	FOREIGN KEY (Country) REFERENCES COUNTRY (Country),
	FOREIGN KEY (Country, City) REFERENCES CITY (Country, City),
	FOREIGN KEY (Review_ID) REFERENCES REVIEWABLE (Review_ID),
FOREIGN KEY (Category) REFERENCES SUPPORTED_EVENTS (MASKEvent) );

CREATE TABLE MANAGER
	(Mgr_Username	VARCHAR(15)			NOT NULL,
	 Mgr_Email		VARCHAR(35)			NOT NULL UNIQUE,
	 UserPassword		VARCHAR(15)			NOT NULL,
	PRIMARY KEY (Mgr_Username) );
    
